# This file was *autogenerated* from the file plot.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4)
A = matrix([[_sage_const_0 , -_sage_const_1 , _sage_const_1 , _sage_const_1 , -_sage_const_1 ],
             [_sage_const_1 , _sage_const_0 , -_sage_const_1 , -_sage_const_1 , _sage_const_1 ],
             [-_sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1  , -_sage_const_1 ],
             [-_sage_const_1 , _sage_const_1 , -_sage_const_1 , _sage_const_0 , _sage_const_1 ],
             [_sage_const_1 , -_sage_const_1 , _sage_const_1 , -_sage_const_1 , _sage_const_0 ]])

clrs = rainbow(_sage_const_5 )
p = plot(x * A[_sage_const_0 , _sage_const_0 ] + (_sage_const_1  - x) * A[_sage_const_0 , _sage_const_4 ], x, _sage_const_0 , _sage_const_1 , legend_label="$u(R)$", color=clrs[_sage_const_0 ], axes_labels=['Proportion of time I play Rock', ''])
p += plot(x * A[_sage_const_1 , _sage_const_0 ] + (_sage_const_1  - x) * A[_sage_const_1 , _sage_const_4 ], x, _sage_const_0 , _sage_const_1 , legend_label="$u(P)$", color=clrs[_sage_const_1 ])
p += plot(x * A[_sage_const_2 , _sage_const_0 ] + (_sage_const_1  - x) * A[_sage_const_2 , _sage_const_4 ], x, _sage_const_0 , _sage_const_1 , legend_label="$u(S)$", color=clrs[_sage_const_2 ])
p += plot(x * A[_sage_const_3 , _sage_const_0 ] + (_sage_const_1  - x) * A[_sage_const_3 , _sage_const_4 ], x, _sage_const_0 , _sage_const_1 , legend_label="$u(Lz)$", color=clrs[_sage_const_3 ])
p += plot(x * A[_sage_const_4 , _sage_const_0 ] + (_sage_const_1  - x) * A[_sage_const_4 , _sage_const_4 ], x, _sage_const_0 , _sage_const_1 , legend_label="$u(Sp)$", color=clrs[_sage_const_4 ])
p.save("plot.pdf")
